### PR TITLE
Language types and health default problem

### PR DESCRIPTION
**Pull request by pvdbosch**
- define default problem response in /health instead of only for status 500
- Add Language/BelgianLanguage types

### CODE REVIEW

**Comment by pvdbosch** [comment]
to verify if aligned with upcoming Language entry in fedvoc

**Comment by pvdbosch** [comment]
WG feedback: in openapi 3 version, move healthcheck responses to components/response and add $refs to them. Referring to the /health path from another API is often problematic in tooling.

**Comment by pvdbosch** [comment]
Language not yet published in fedvoc (draft decision in https://fedictaim.atlassian.net/wiki/spaces/JCSP/pages/18516082855/2023-03-02+Meeting+notes - next functional WG June 9th).

**Comment by jpraet** [comment]
Can we update the description of the /health resource? It is currently SMALS-specific
`description: This resource is only available to supervision users`

**Comment by pvdbosch** [comment]
I'll update the description

**Comment by pvdbosch** [comment]
(Belgian)Language was also reviewed by functional WG, so merging

**Pull request merged**
